
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.compi1.interprete;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int OPC_LET_BLOQ = 49;
  public static final int OPC_FIG_MIE = 43;
  public static final int OPC_LET_SIZE_MIE = 45;
  public static final int ASIGNAR = 14;
  public static final int MULT = 17;
  public static final int OPC_COLOR_TXT_MIE = 41;
  public static final int FIG_ELIPSE = 51;
  public static final int OPC_COLOR_TXT_BLOQ = 46;
  public static final int ENTERO = 31;
  public static final int SI = 5;
  public static final int MOSTRAR = 11;
  public static final int DIFERENTE = 22;
  public static final int RESTA = 16;
  public static final int LPAREN = 19;
  public static final int ENTONCES = 6;
  public static final int FIG_RECT = 54;
  public static final int HEX = 61;
  public static final int OPC_COLOR_MIE = 42;
  public static final int SEPARADOR = 13;
  public static final int FIG_RECT_RED = 56;
  public static final int FIN = 3;
  public static final int OPC_LET_SIZE_SI = 40;
  public static final int RPAREN = 20;
  public static final int FIN_SI = 7;
  public static final int NOT = 29;
  public static final int AND = 27;
  public static final int FIG_PARALELO = 53;
  public static final int LET_VERDANA = 60;
  public static final int IGUALDAD = 21;
  public static final int OR = 28;
  public static final int MIENTRAS = 8;
  public static final int DIV = 18;
  public static final int OPC_FIG_SI = 38;
  public static final int SUMA = 15;
  public static final int FIG_ROMBO = 55;
  public static final int OPC_LET_MIE = 44;
  public static final int LET_ARIAL = 57;
  public static final int ID = 30;
  public static final int EOF = 0;
  public static final int DECIMAL = 32;
  public static final int error = 1;
  public static final int COMA = 63;
  public static final int PIPE = 62;
  public static final int CADENA = 33;
  public static final int MENOR = 26;
  public static final int FIN_MIENTRAS = 10;
  public static final int ERROR_LEXICO = 34;
  public static final int MAYOR = 25;
  public static final int LET_COMIC = 59;
  public static final int LET_TIMES = 58;
  public static final int OPC_COLOR_SI = 37;
  public static final int MAYOR_IGUAL = 23;
  public static final int FIG_CIRCULO = 52;
  public static final int LEER = 12;
  public static final int OPC_LET_SIZE_BLOQ = 50;
  public static final int OPC_FIG_BLOQ = 48;
  public static final int HACER = 9;
  public static final int OPC_DEFAULT = 35;
  public static final int INICIO = 2;
  public static final int OPC_COLOR_TXT_SI = 36;
  public static final int MENOR_IGUAL = 24;
  public static final int OPC_LET_SI = 39;
  public static final int OPC_COLOR_BLOQ = 47;
  public static final int VAR = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INICIO",
  "FIN",
  "VAR",
  "SI",
  "ENTONCES",
  "FIN_SI",
  "MIENTRAS",
  "HACER",
  "FIN_MIENTRAS",
  "MOSTRAR",
  "LEER",
  "SEPARADOR",
  "ASIGNAR",
  "SUMA",
  "RESTA",
  "MULT",
  "DIV",
  "LPAREN",
  "RPAREN",
  "IGUALDAD",
  "DIFERENTE",
  "MAYOR_IGUAL",
  "MENOR_IGUAL",
  "MAYOR",
  "MENOR",
  "AND",
  "OR",
  "NOT",
  "ID",
  "ENTERO",
  "DECIMAL",
  "CADENA",
  "ERROR_LEXICO",
  "OPC_DEFAULT",
  "OPC_COLOR_TXT_SI",
  "OPC_COLOR_SI",
  "OPC_FIG_SI",
  "OPC_LET_SI",
  "OPC_LET_SIZE_SI",
  "OPC_COLOR_TXT_MIE",
  "OPC_COLOR_MIE",
  "OPC_FIG_MIE",
  "OPC_LET_MIE",
  "OPC_LET_SIZE_MIE",
  "OPC_COLOR_TXT_BLOQ",
  "OPC_COLOR_BLOQ",
  "OPC_FIG_BLOQ",
  "OPC_LET_BLOQ",
  "OPC_LET_SIZE_BLOQ",
  "FIG_ELIPSE",
  "FIG_CIRCULO",
  "FIG_PARALELO",
  "FIG_RECT",
  "FIG_ROMBO",
  "FIG_RECT_RED",
  "LET_ARIAL",
  "LET_TIMES",
  "LET_COMIC",
  "LET_VERDANA",
  "HEX",
  "PIPE",
  "COMA"
  };
}

